//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClient.GetLondonCustomersServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="GetLondonCustomersServiceReference.ILondonCustomers")]
    public interface ILondonCustomers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ILondonCustomers/GetLondonCustomers", ReplyAction="http://Microsoft.ServiceModel.Samples/ILondonCustomers/GetLondonCustomersResponse" +
            "")]
        string GetLondonCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ILondonCustomers/GetLondonCustomers", ReplyAction="http://Microsoft.ServiceModel.Samples/ILondonCustomers/GetLondonCustomersResponse" +
            "")]
        System.Threading.Tasks.Task<string> GetLondonCustomersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILondonCustomersChannel : MyClient.GetLondonCustomersServiceReference.ILondonCustomers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LondonCustomersClient : System.ServiceModel.ClientBase<MyClient.GetLondonCustomersServiceReference.ILondonCustomers>, MyClient.GetLondonCustomersServiceReference.ILondonCustomers {
        
        public LondonCustomersClient() {
        }
        
        public LondonCustomersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LondonCustomersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LondonCustomersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LondonCustomersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLondonCustomers() {
            return base.Channel.GetLondonCustomers();
        }
        
        public System.Threading.Tasks.Task<string> GetLondonCustomersAsync() {
            return base.Channel.GetLondonCustomersAsync();
        }
    }
}
